# Generated by Django 5.2.9 on 2025-12-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('DTD', 'Door-to-Door'), ('FCL', 'Full Container Load'), ('LCL', 'Less than Container Load')], max_length=10)),
                ('origin', models.CharField(choices=[('NA', 'North America'), ('CN', 'China'), ('EU', 'Europe')], max_length=2)),
                ('destination_country', models.CharField(choices=[('NG', 'Nigeria'), ('GH', 'Ghana'), ('CI', "Côte d'Ivoire"), ('SN', 'Senegal'), ('BJ', 'Benin'), ('TG', 'Togo'), ('ML', 'Mali'), ('BF', 'Burkina Faso'), ('GM', 'Gambia'), ('SL', 'Sierra Leone'), ('CM', 'Cameroon'), ('CG', 'Congo (Republic)'), ('CD', 'DR Congo'), ('GA', 'Gabon'), ('TD', 'Chad'), ('CF', 'Central African Republic'), ('GQ', 'Equatorial Guinea')], max_length=2)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_time_days', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
