# Generated by Django 5.2.9 on 2026-01-04 21:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('FCL', 'Full Container Load'), ('LCL', 'Less than Container Load'), ('DTD', 'Door to Door')], max_length=10)),
                ('origin_region', models.CharField(choices=[('north_america', 'North America'), ('china', 'China'), ('europe', 'Europe')], max_length=50)),
                ('destination_country', models.CharField(choices=[('NG', 'Nigeria'), ('GH', 'Ghana'), ('CI', "Côte d'Ivoire"), ('SN', 'Senegal'), ('BJ', 'Benin'), ('TG', 'Togo'), ('ML', 'Mali'), ('BF', 'Burkina Faso'), ('GM', 'Gambia'), ('SL', 'Sierra Leone'), ('CM', 'Cameroon'), ('CG', 'Congo (Republic)'), ('CD', 'DR Congo'), ('GA', 'Gabon'), ('TD', 'Chad'), ('CF', 'Central African Republic'), ('GQ', 'Equatorial Guinea')], max_length=50)),
                ('maersk_ocean_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking_fee', models.DecimalField(decimal_places=2, default=600.0, max_digits=10)),
                ('quoted_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('origin_address', models.TextField()),
                ('dropoff_date', models.DateField(blank=True, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('quote_status', models.CharField(choices=[('new', 'New'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote_sent_at', models.DateTimeField(blank=True, null=True)),
                ('quote_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('stripe', 'Credit / Debit Card (Apple Pay supported)'), ('cashapp', 'Cash App'), ('zelle', 'Zelle'), ('wire', 'Wire Transfer')], max_length=20, null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
