# Generated by Django 5.2.9 on 2025-12-22 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_country', models.CharField(choices=[('north_america', 'North America'), ('china', 'China'), ('europe', 'Europe')], max_length=50)),
                ('destination_country', models.CharField(choices=[('NG', 'Nigeria'), ('GH', 'Ghana'), ('CI', "Côte d'Ivoire"), ('SN', 'Senegal'), ('BJ', 'Benin'), ('TG', 'Togo'), ('ML', 'Mali'), ('BF', 'Burkina Faso'), ('GM', 'Gambia'), ('SL', 'Sierra Leone'), ('CM', 'Cameroon'), ('CG', 'Congo (Republic)'), ('CD', 'DR Congo'), ('GA', 'Gabon'), ('TD', 'Chad'), ('CF', 'Central African Republic'), ('GQ', 'Equatorial Guinea')], max_length=50)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('volume_cbm', models.DecimalField(decimal_places=2, help_text='Cubic meters (CBM)', max_digits=8)),
                ('pickup_required', models.BooleanField(default=False)),
                ('pickup_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('shipping_address', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('card', 'Credit / Debit Card'), ('bank', 'Bank Transfer'), ('wire', 'Wire Transfer'), ('cashapp', 'Cash App'), ('zelle', 'Zelle'), ('applepay', 'Apple Pay'), ('cash', 'Cash')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
