# Generated by Django 5.2.9 on 2025-12-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_user_order_customer_remove_order_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dropoff_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='origin_address',
            field=models.TextField(default='FCL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
