# Generated by Django 5.2.9 on 2025-12-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_status_order_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Credit / Debit Card (Apple Pay supported)'), ('cashapp', 'Cash App'), ('zelle', 'Zelle'), ('wire', 'Wire Transfer')], max_length=20, null=True),
        ),
    ]
